- git:
    uri: https://github.com/open-rdc/orne-box
    local-name: orne-box
    version: noetic-devel

- git:
    uri: https://github.com/open-rdc/adi_driver
    local-name: adi_driver
    version: master

- git:
    uri: https://github.com/open-rdc/icart
    local-name: icart
    version: noetic-devel

- git:
    uri: https://github.com/open-rdc/ypspur
    local-name: ypspur
    version: noetic-devel
